service: mailshrimp
app: mailshrimp
org: josejuniorr

frameworkVersion: "2"

provider:
  name: aws
  stage: dev
  lambdaHashingVersion: 20201221
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"
  environment:
    MS_URL_MESSAGES: ${param:MS_URL_MESSAGES}
    MS_JWT_SECRET: ${param:MS_JWT_SECRET}
    MS_JWT_EXPIRES: ${param:MS_JWT_EXPIRES}
  tags:
    STAGE: prd
    PROJECT: mailshrimp

  deploymentBucket:
    name: ${self:service}-prd-deployment
    AccessControl: PublicRead
    tags:
      STAGE: ${self:provider.stage}
      PROJETO: ${self:service}

plugins:
  - serverless-layers

custom:
  serverless-layers:
    dependenciesPath: ./package.json

    
functions:
  send-message:
    name: ${opt:stage, self:provider.stage}-${self:service}-send-message
    description: "Envia o e-mail"
    handler: src/handlers/send-message/index.sendMessage
    memorySize: 128
    timeout: 60
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:400016104213:Mailshrimp.fifo
          batchSize: 1
