service: mailshrimp
app: mailshrimp
org: josejuniorr
frameworkVersion: "2"

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: "*"
  environment:
    MS_URL_MESSAGES: ${param:MS_URL_MESSAGES}
    MS_JWT_SECRET: ${param:MS_JWT_SECRET}
    MS_JWT_EXPIRES: ${param:MS_JWT_EXPIRES}
  tags:
    STAGE: prd
    PROJECT: mailshrimp

  deploymentBucket:
    name: mailshrimp-dev-serverlessdeploymentbucket-kwhg3opfb5t7
    tags:
      STAGE: ${self:provider.stage}
      PROJETO: ${self:service}

  plugins:
    serverless-layers:
      dependenciesPath: ./package.json

functions:
  send-message:
    name: ${opt:stage, self:provider.stage}-${self:service}-send-message
    description: "Envia o e-mail"
    handler: src/handlers/send-message/index.sendMessage
    memorySize: 128
    timeout: 30
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:400016104213:mailshrimp
          batchSize: 1
